import "../styles/globals.css";
import { wrapper, store } from "../store/store";
// import { Provider } from "react-redux";
import reduxWrapper from "../store/store";
import App from "next/app";
import Head from "next/head";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Swivel Practical Assignement</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

MyApp.getInitialProps = reduxWrapper.getInitialAppProps(
  (store) => async (appContext) => {
    return {
      ...(await App.getInitialProps(appContext)),
      store,
    };
  }
);

export default reduxWrapper.withRedux(MyApp);
